# Generated by Django 5.1.2 on 2026-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_admin_role_support_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('essay', 'مقالي')], default='mcq', max_length=20),
        ),
    ]
