# Generated by Django 5.1.2 on 2026-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
